version: 2
jobs: # we now have TWO jobs, so that a workflow can coordinate them!
  build: # This is our first job.
    docker: # it uses the docker executor
      - image: circleci/node # specifically, a docker image with ruby 2.4.1
    # Steps are a list of commands to run inside the docker container above.
    steps:
      - checkout # this pulls code down from GitHub
      - run: echo "npm installing" # This prints "A first hello" to stdout.
      - run: npm install
  test: # This is our second job.
    docker: # it runs inside a docker image, the same as above.
      - image: circleci/node
    steps:
      - checkout
      - run: echo "A more familiar hi" # We run a similar echo command to above.
      - run: npm install
      - run: mpm run test
        test: # This is our second job.
    docker: # it runs inside a docker image, the same as above.
      - image: circleci/node
    steps:
      - checkout
      - run: echo "A more familiar hi" # We run a similar echo command to above.
      - run: npm install
      - run: mpm run test
# Under the workflows: map, we can coordinate our two jobs, defined above.
  hellooo: 
    docker: # it uses the docker executor
      - image: circleci/node 
    steps:
      - checkout # this pulls code down from GitHub
      - run: echo "Helloooo"
workflows:
  version: 2
  one_and_two: # this is the name of our workflow
    jobs: # and here we list the jobs we are going to run.
      - build
      - test:
          requires:
            - hellooo